
seed: 2022
log_interval: 100
num_workers: 4
batch_type: numel
batch_size: 16
batch_bins: 1000000
accum_grad: 4
grad_clip: 1.0
max_epoch: 5
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 3
use_amp: false

optim: adamw
optim_conf:
    lr: 0.0001
    weight_decay: 0.000001
# scheduler: warmuplr
# scheduler_conf:
#     warmup_steps: 6000
