
seed: 2022
log_interval: 1
num_workers: 1
batch_type: unsorted
batch_size: 2
batch_bins: 1000000
accum_grad: 1
grad_clip: 1.0
max_epoch: 5
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 2
use_amp: false

optim: adamw
optim_conf:
    lr: 0.0001
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 6000
